---
name: Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  conform:
    runs-on: ubuntu-latest
    name: Conform

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: siderolabs/conform@v0.1.0-alpha.27
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  preview:
    runs-on: ubuntu-latest
    name: Pulumi Preview
    strategy:
      max-parallel: 12
      matrix:
        node-version: ["16"]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: |
          npm install -g yarn

      - run: |
          yarn install
          yarn build

      - uses: pulumi/actions@v4
        with:
          command: preview
          stack-name: prod
        env:
          CLOUDSDK_COMPUTE_REGION: "${{ secrets.CLOUDSDK_COMPUTE_REGION }}"
          CLOUDSDK_CORE_PROJECT: "${{ secrets.CLOUDSDK_CORE_PROJECT }}"
          PULUMI_ACCESS_TOKEN: "${{ secrets.PULUMI_ACCESS_TOKEN }}"
          GOOGLE_CREDENTIALS: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}"

  deploy:
    runs-on: ubuntu-latest
    name: Pulumi Deploy
    needs:
      - preview
    strategy:
      max-parallel: 12
      matrix:
        node-version: ["16"]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: |
          npm install -g yarn

      - run: |
          yarn install
          yarn build

      - uses: pulumi/actions@v4
        with:
          command: up
          stack-name: prod
        env:
          CLOUDSDK_COMPUTE_REGION: "${{ secrets.CLOUDSDK_COMPUTE_REGION }}"
          CLOUDSDK_CORE_PROJECT: "${{ secrets.CLOUDSDK_CORE_PROJECT }}"
          PULUMI_ACCESS_TOKEN: "${{ secrets.PULUMI_ACCESS_TOKEN }}"
          GOOGLE_CREDENTIALS: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}"
